version: "2"

services:
  voting-app:
    build: ./voting-app/.
    logging: &log_config
      driver: ${COMPOSE_LOG_DRIVER}
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    logging: *log_config
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    logging: *log_config
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    logging: *log_config
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    logging: *log_config
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:


